AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WhileUntilModifier:
  MaxLineLength: 120
